export const AVAILABLE_LABELS = [
  'Circles',
  'Lisbon',
  'Zanzibar',
  'London',
  'Los Angeles',
  'Porto',
  'Benin',
  'Translators',
  'Designers',
  'Developers',
  'Event Organisers',
  'Writers',
  'Other',
] as const
